"""empty message

Revision ID: 070333359d46
Revises: cd8d7304aef4
Create Date: 2019-11-06 01:10:02.303440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070333359d46'
down_revision = 'cd8d7304aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'participans_fk_ticketid_fkey', 'participans', type_='foreignkey')
    op.drop_column('participans', 'fk_ticketid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participans', sa.Column('fk_ticketid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'participans_fk_ticketid_fkey', 'participans', 'tickets', ['fk_ticketid'], ['id'])
    # ### end Alembic commands ###
