"""empty message

Revision ID: 26b596bcbb1c
Revises: d21300b22dbd
Create Date: 2019-11-06 02:19:14.630633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b596bcbb1c'
down_revision = 'd21300b22dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('participan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'participans', ['participan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'participan_id')
    # ### end Alembic commands ###
