"""empty message

Revision ID: 5eab70d11f52
Revises: ff1df42e742c
Create Date: 2019-11-05 23:22:50.729766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eab70d11f52'
down_revision = 'ff1df42e742c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_ticketid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('phone', sa.String(length=300), nullable=False),
    sa.Column('qrcode', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_ticketid'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participans')
    # ### end Alembic commands ###
