"""empty message

Revision ID: d21300b22dbd
Revises: 070333359d46
Create Date: 2019-11-06 01:13:04.191836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21300b22dbd'
down_revision = '070333359d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participans', sa.Column('fk_ticket', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participans', 'tickets', ['fk_ticket'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participans', type_='foreignkey')
    op.drop_column('participans', 'fk_ticket')
    # ### end Alembic commands ###
