"""empty message

Revision ID: e15262a25a49
Revises: a156dbc5392b
Create Date: 2019-11-05 23:10:55.263943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15262a25a49'
down_revision = 'a156dbc5392b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_qrcode', sa.Integer(), nullable=False))
    op.drop_column('tickets', 'ticket_qtys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_qtys', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tickets', 'ticket_qrcode')
    # ### end Alembic commands ###
