"""empty message

Revision ID: ff1df42e742c
Revises: e15262a25a49
Create Date: 2019-11-05 23:13:56.073439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1df42e742c'
down_revision = 'e15262a25a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_qty', sa.Integer(), nullable=False))
    op.drop_column('tickets', 'ticket_qrcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_qrcode', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tickets', 'ticket_qty')
    # ### end Alembic commands ###
